using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace relert_sharp.FileSystem
{
    public class TextFile : BaseFile
    {



        #region Constructor - TextFile
        public TextFile(string path, FileMode m, FileAccess a) : base(path, m, a)
        {
            WriteLine(";Plain Text File Generated by Relert-Sharp");
        }
        #endregion


        #region Public Methods - TextFile
        public void WriteString(string toWrite)
        {
            Write(toWrite);
        }
        public void WriteLine(string s)
        {
            WriteString(s); WriteString("\r\n");
        }
        #endregion
    }
}
