using System.IO;

namespace RelertSharp.FileSystem
{
    public class TextFile : BaseFile
    {



        #region Ctor - TextFile
        public TextFile(string path, FileMode m, FileAccess a) : base(path, m, a)
        {
            WriteLine(";Plain Text File Generated by Relert-Sharp");
        }
        #endregion


        #region Public Methods - TextFile
        public void WriteString(string toWrite)
        {
            Write(toWrite);
        }
        public void WriteLine(string s)
        {
            WriteString(s); WriteString("\r\n");
        }
        #endregion
    }
}
